# Generated by Django 6.0.4 on 2026-04-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bus_number', models.CharField(max_length=50, unique=True)),
                ('route', models.CharField(max_length=100)),
                ('boarding_point', models.CharField(max_length=100)),
                ('dropping_point', models.CharField(max_length=100)),
                ('departure_time', models.TimeField()),
                ('total_seats', models.IntegerField(default=40)),
                ('available_seats', models.IntegerField(default=40)),
            ],
        ),
    ]
