# Generated by Django 6.0.3 on 2026-04-17 12:39

import api.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_bus_bus_number_alter_bus_name_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='bus_id_code',
            field=models.CharField(default=api.models.generate_bus_id, max_length=6, unique=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bus',
            name='fare',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Checker', 'Checker'), ('Vendor', 'Vendor')], default='Student', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Used', 'Used'), ('Expired', 'Expired')], default='Active', max_length=20),
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'Vendor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SOSAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studentprofile')),
            ],
        ),
    ]
