# Generated by Django 6.0.3 on 2026-04-17 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_bus_bus_id_code_bus_date_bus_fare_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
