# Generated by Django 6.0.3 on 2026-04-17 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_bus_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('boarding_point', models.CharField(max_length=100)),
                ('dropping_point', models.CharField(max_length=100)),
                ('fare', models.DecimalField(decimal_places=2, default=10.0, max_digits=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='bus',
            name='boarding_point',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='dropping_point',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='fare',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='bus',
        ),
        migrations.AddField(
            model_name='bus',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='bus_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.bus'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.route'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='api.route'),
        ),
    ]
