# Generated by Django 6.0.3 on 2026-04-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_route_remove_bus_boarding_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
