# Generated by Django 6.0.3 on 2026-04-17 17:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_vehicle_is_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='sosalert',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='ticket',
            name='travel_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='notice',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Vendor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.studentprofile'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
