# Generated by Django 6.0.3 on 2026-04-17 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_notice_options_alter_sosalert_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. DSC-Dhanmondi', max_length=100)),
                ('boarding_point', models.CharField(max_length=100)),
                ('dropping_point', models.CharField(max_length=100)),
                ('fare', models.DecimalField(decimal_places=2, default=80.0, max_digits=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='route',
            name='boarding_point',
        ),
        migrations.RemoveField(
            model_name='route',
            name='dropping_point',
        ),
        migrations.RemoveField(
            model_name='route',
            name='fare',
        ),
        migrations.RemoveField(
            model_name='route',
            name='name',
        ),
        migrations.AlterField(
            model_name='route',
            name='schedule_time',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='master_route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.masterroute'),
        ),
    ]
