# Generated by Django 6.0.3 on 2026-04-18 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_masterroute_remove_route_boarding_point_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='route',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='route',
        ),
        migrations.AddField(
            model_name='bus',
            name='master_route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='api.masterroute'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='desired_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='master_route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.masterroute'),
        ),
    ]
